from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg
import pandas as pd
import numpy as np
from sklearn import preprocessing
import Neiron


class Ui_MainWindow(object):
    train = pd.read_csv('Pisy.csv')
    data1 = train['Unnamed: 0'].to_numpy()
    data2 = train['0'].to_numpy()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1198, 746)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(1920, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.Mainloyaut = QtWidgets.QGridLayout()
        self.Mainloyaut.setObjectName("Mainloyaut")
        self.IdVerdiktNomerNomerTextLayout = QtWidgets.QGridLayout()
        self.IdVerdiktNomerNomerTextLayout.setObjectName("IdVerdiktNomerNomerTextLayout")
        self.verdickt_box = QtWidgets.QGroupBox(self.centralwidget)
        self.verdickt_box.setObjectName("verdickt_box")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.verdickt_box)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verdict_label = QtWidgets.QLabel(self.verdickt_box)
        self.verdict_label.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.verdict_label.setAlignment(QtCore.Qt.AlignCenter)
        self.verdict_label.setObjectName("verdict_label")
        self.gridLayout_7.addWidget(self.verdict_label, 0, 0, 1, 1)
        self.IdVerdiktNomerNomerTextLayout.addWidget(self.verdickt_box, 0, 2, 2, 1)
        self.textvoprosa_box = QtWidgets.QGroupBox(self.centralwidget)
        self.textvoprosa_box.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.textvoprosa_box.setObjectName("textvoprosa_box")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.textvoprosa_box)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.textvoprosa_label = QtWidgets.QLabel(self.textvoprosa_box)
        self.textvoprosa_label.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.textvoprosa_label.setObjectName("textvoprosa_label")
        self.gridLayout_8.addWidget(self.textvoprosa_label, 0, 0, 1, 1)
        self.IdVerdiktNomerNomerTextLayout.addWidget(self.textvoprosa_box, 2, 0, 1, 3)
        self.nomertest_box = QtWidgets.QGroupBox(self.centralwidget)
        self.nomertest_box.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.nomertest_box.setObjectName("nomertest_box")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.nomertest_box)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.nomertest = QtWidgets.QLabel(self.nomertest_box)
        self.nomertest.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.nomertest.setAlignment(QtCore.Qt.AlignCenter)
        self.nomertest.setObjectName("nomertest")
        self.gridLayout_5.addWidget(self.nomertest, 0, 0, 1, 1)
        self.IdVerdiktNomerNomerTextLayout.addWidget(self.nomertest_box, 1, 0, 1, 1)
        self.nomerpovtora_box = QtWidgets.QGroupBox(self.centralwidget)
        self.nomerpovtora_box.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.nomerpovtora_box.setObjectName("nomerpovtora_box")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.nomerpovtora_box)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.nomervoprosa_label = QtWidgets.QLabel(self.nomerpovtora_box)
        self.nomervoprosa_label.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.nomervoprosa_label.setAlignment(QtCore.Qt.AlignCenter)
        self.nomervoprosa_label.setObjectName("nomervoprosa_label")
        self.gridLayout_6.addWidget(self.nomervoprosa_label, 0, 0, 1, 1)
        self.IdVerdiktNomerNomerTextLayout.addWidget(self.nomerpovtora_box, 1, 1, 1, 1)
        self.Id_ispt_box = QtWidgets.QGroupBox(self.centralwidget)
        self.Id_ispt_box.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.Id_ispt_box.setObjectName("Id_ispt_box")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Id_ispt_box)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.id_ispt_label = QtWidgets.QLabel(self.Id_ispt_box)
        self.id_ispt_label.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.id_ispt_label.setAlignment(QtCore.Qt.AlignCenter)
        self.id_ispt_label.setObjectName("id_ispt_label")
        self.gridLayout_4.addWidget(self.id_ispt_label, 0, 0, 1, 1)
        self.IdVerdiktNomerNomerTextLayout.addWidget(self.Id_ispt_box, 0, 0, 1, 2)
        self.Mainloyaut.addLayout(self.IdVerdiktNomerNomerTextLayout, 0, 1, 1, 1)

        self.plotGrid = QtWidgets.QGridLayout()
        self.plotGrid.setObjectName("plotGrid")
        # self.PlotFrame = QtWidgets.QFrame(self.centralwidget)
        # self.PlotFrame.setStyleSheet("background-color: rgb(188, 188, 188);")
        # self.PlotFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        # self.PlotFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        # elf.PlotFrame.setObjectName("PlotFrame")
        pg.setConfigOption('background', 'w')
        self.PlotFrame = pg.PlotWidget()
        self.plotGrid.addWidget(self.PlotFrame)





        time = list(i for i in range(len(self.data1)))
        for i in range(0, len(self.data2)):
            self.data2[i] = self.data2[i] + 4000

        # ras = list(-3000 for i in range(240))
        # for i in range(0, len(data2)):
        #    if i%12==0:
        #        ras[i]=6000

        # plot data: x, y values
        self.PlotFrame.plot(time, self.data1, pen=(255, 0, 0))
        self.PlotFrame.plot(time, self.data2, pen=(0, 255, 0))
        inf1 = pg.InfiniteLine(movable=False, angle=90, label='Вопрос 1')
        inf2 = pg.InfiniteLine(movable=False, angle=90, label='Вопрос 2')
        inf3 = pg.InfiniteLine(movable=False, angle=90, label='Вопрос 3')
        inf4 = pg.InfiniteLine(movable=False, angle=90, label='Вопрос 4')
        inf5 = pg.InfiniteLine(movable=False, angle=90, label='Вопрос 5')
        inf6 = pg.InfiniteLine(movable=False, angle=90, label='Вопрос 6')
        inf7 = pg.InfiniteLine(movable=False, angle=90, label='Вопрос 7')
        inf8 = pg.InfiniteLine(movable=False, angle=90, label='Вопрос 8')
        inf9 = pg.InfiniteLine(movable=False, angle=90, label='Вопрос 9')
        inf10 = pg.InfiniteLine(movable=False, angle=90, label='Вопрос 10')
        inf11 = pg.InfiniteLine(movable=False, angle=90, label='Вопрос 11')
        inf12 = pg.InfiniteLine(movable=False, angle=90, label='Вопрос 12')
        inf2.setPos([240, 0])
        inf3.setPos([480, 0])
        inf4.setPos([720, 0])
        inf5.setPos([960, 0])
        inf6.setPos([1200, 0])
        inf7.setPos([1440, 0])
        inf8.setPos([1680, 0])
        inf9.setPos([1920, 0])
        inf10.setPos([2160, 0])
        inf11.setPos([2400, 0])
        inf12.setPos([2640, 0])

        self.PlotFrame.addItem(inf1)
        self.PlotFrame.addItem(inf2)
        self.PlotFrame.addItem(inf3)
        self.PlotFrame.addItem(inf4)
        self.PlotFrame.addItem(inf5)
        self.PlotFrame.addItem(inf6)
        self.PlotFrame.addItem(inf7)
        self.PlotFrame.addItem(inf8)
        self.PlotFrame.addItem(inf9)
        self.PlotFrame.addItem(inf10)
        self.PlotFrame.addItem(inf11)
        self.PlotFrame.addItem(inf12)

        # self.PlotFrame.plot(time, ras, pen=(0,0,255))

        self.plotGrid.addWidget(self.PlotFrame, 0, 0, 1, 1)
        self.Mainloyaut.addLayout(self.plotGrid, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(1308, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Mainloyaut.addItem(spacerItem, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 458, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Mainloyaut.addItem(spacerItem1, 1, 2, 1, 1)
        self.derevoGrid = QtWidgets.QGridLayout()
        self.derevoGrid.setObjectName("derevoGrid")
        self.Derevo_box = QtWidgets.QGroupBox(self.centralwidget)
        self.Derevo_box.setObjectName("Derevo_box")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Derevo_box)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeWidget = QtWidgets.QTreeWidget(self.Derevo_box)
        self.treeWidget.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.itemClicked.connect(self.treeWitgedClicked)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        #item_1 = QtWidgets.QTreeWidgetItem(item_0)
        #item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        QtWidgets.QTreeWidgetItem(self.treeWidget)
        QtWidgets.QTreeWidgetItem(self.treeWidget)
        QtWidgets.QTreeWidgetItem(self.treeWidget)
        QtWidgets.QTreeWidgetItem(self.treeWidget)
        QtWidgets.QTreeWidgetItem(self.treeWidget)
        QtWidgets.QTreeWidgetItem(self.treeWidget)
        QtWidgets.QTreeWidgetItem(self.treeWidget)
        QtWidgets.QTreeWidgetItem(self.treeWidget)
        QtWidgets.QTreeWidgetItem(self.treeWidget)
        QtWidgets.QTreeWidgetItem(self.treeWidget)
        #item_1 = QtWidgets.QTreeWidgetItem(item_0)
        i#tem_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.gridLayout_2.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.derevoGrid.addWidget(self.Derevo_box, 0, 0, 1, 1)
        self.Mainloyaut.addLayout(self.derevoGrid, 0, 0, 2, 1)
        self.gridLayout_12.addLayout(self.Mainloyaut, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.verdickt_box.setTitle(_translate("MainWindow", "Вердикт"))
        self.verdict_label.setText(_translate("MainWindow", "Выберете вопрос"))
        self.textvoprosa_box.setTitle(_translate("MainWindow", "Текст вопроса"))
        self.textvoprosa_label.setText(_translate("MainWindow", "Победит ли ИИнтеграция в хакатоне ?"))
        self.nomertest_box.setTitle(_translate("MainWindow", "Номер теста"))
        self.nomertest.setText(_translate("MainWindow", "1"))
        self.nomerpovtora_box.setTitle(_translate("MainWindow", "Номер повтора"))
        self.nomervoprosa_label.setText(_translate("MainWindow", "1"))
        self.Id_ispt_box.setTitle(_translate("MainWindow", "Id испытуемого"))
        self.id_ispt_label.setText(_translate("MainWindow", "Жмышенко Валерий Альбертович"))
        self.Derevo_box.setTitle(_translate("MainWindow", "Дерево вопросов"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Вопросы"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "1"))
        #self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "1 (Котики или Щеночки)"))
        #self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "2 (Кто Где Когда)"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "2"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "3"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "4"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "5"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("MainWindow", "6"))
        self.treeWidget.topLevelItem(6).setText(0, _translate("MainWindow", "7"))
        self.treeWidget.topLevelItem(7).setText(0, _translate("MainWindow", "8"))
        self.treeWidget.topLevelItem(8).setText(0, _translate("MainWindow", "9"))
        self.treeWidget.topLevelItem(9).setText(0, _translate("MainWindow", "10"))
        self.treeWidget.topLevelItem(10).setText(0, _translate("MainWindow", "11"))
        self.treeWidget.topLevelItem(11).setText(0, _translate("MainWindow", "12"))

        #self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "1 (Зачем она мне)"))
        #self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "2 (Котики или Щеночки)"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)

    def treeWitgedClicked(self,it,col):
        data1resh = np.reshape(self.data1,(2640, 1))
        data2resh = np.reshape(self.data2,(2640, 1))
        scaler = preprocessing.QuantileTransformer().fit(data1resh)
        scaler_2 = preprocessing.QuantileTransformer().fit(data2resh)
        data1preproc = scaler.transform(data1resh)
        print(data1preproc)
        data2preproc = scaler_2.transform(data2resh)
        print(data2preproc)
        print(it.text(col))
        self.nomervoprosa_label.setText(it.text(col))
        num = int(it.text(col))
        mass1 = data1preproc[(240*num)-240:240 * num]
        mass1 = np.reshape(mass1,(1,240))
        mass2 = data2preproc[(240 * num) - 240:240 * num]
        mass2 = np.reshape(mass2, (1,240))
        otvet = Neiron.predict_models(mass1,mass2)
        print(otvet)
        if otvet[2] == 0:
            self.verdict_label.setText('Низкий стресс')
        elif otvet[2] == 1:
            self.verdict_label.setText('Средний стресс')
        elif otvet[2] == 2:
            self.verdict_label.setText('Высокий стресс')
if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
